### ISSUE TITLE
AJAX error

### ISSUE THREAD

**Issue by cmpsoares91** [cmpsoares91/Trabalho-ISMAT-CD#1]
``` sh
/home/oneprovider/Trabalho-ISMAT-CD/Cliente/client.js:67
        $.ajax({
          ^
TypeError: Object function ( w ) {
                                if ( !w.document ) {
                                        throw new Error( "jQuery requires a window with a document" );
                                }
                                return factory( w );
                        } has no method 'ajax'
    at new postJob (/home/oneprovider/Trabalho-ISMAT-CD/Cliente/client.js:67:4)
    at main (/home/oneprovider/Trabalho-ISMAT-CD/Cliente/client.js:124:34)
    at Object.<anonymous> (/home/oneprovider/Trabalho-ISMAT-CD/Cliente/client.js:53:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

**Comment by saguim** [comment]
https://github.com/UncoolAJ86/node-jquery

**Comment by saguim** [comment]
http://www.hacksparrow.com/jquery-with-node-js.html
